config/routes.rb
CrudTest::Application.routes.draw do
  resources :countries
  resources :states

  root  to: 'countries#index'

end

app/models/country.rb
# == Schema Information
#
# Table name: countries
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  iso_code   :string(255)
#

class Country < ActiveRecord::Base
  attr_accessible :iso_code, :name

  has_many :states

  validates :iso_code, presence: true, length: { maximum: 3 }, uniqueness: { case_sensitive: false }
  validates :name, presence: true, length: { maximum: 50 }

  before_save { |country| country.iso_code = iso_code.upcase }
end

app/models/state.rb
class State < ActiveRecord::Base
	attr_accessible :country_iso_code, :state_code, :name

	belongs_to :country

	validates :country_iso_code, presence: true, length: { maximum: 3 }
	validates :state_code, presence: true
	validates :name, presence: true, length: { maximum: 50 }

	validates_uniqueness_of :state_code, :scope => [:country_iso_code]

	before_save do |state| 
		state.country_iso_code = country_iso_code.upcase
		state.state_code = state_code.upcase
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/countries_controller.rb
class CountriesController < ApplicationController
  # GET /countries
  # GET /countries.json
  def index
    @countries = Country.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @countries }
    end
  end

  # GET /countries/1
  # GET /countries/1.json
  def show
    @country = Country.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @country }
    end
  end

  # GET /countries/new
  # GET /countries/new.json
  def new
    @country = Country.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @country }
    end
  end

  # GET /countries/1/edit
  def edit
    @country = Country.find(params[:id])
  end

  # POST /countries
  # POST /countries.json
  def create
    @country = Country.new(params[:country])

    respond_to do |format|
      if @country.save
        format.html { redirect_to @country, notice: 'Country was successfully created.' }
        format.json { render json: @country, status: :created, location: @country }
      else
        format.html { render action: "new" }
        format.json { render json: @country.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /countries/1
  # PUT /countries/1.json
  def update
    @country = Country.find(params[:id])

    respond_to do |format|
      if @country.update_attributes(params[:country])
        format.html { redirect_to @country, notice: 'Country was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @country.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /countries/1
  # DELETE /countries/1.json
  def destroy
    @country = Country.find(params[:id])
    @country.destroy

    respond_to do |format|
      format.html { redirect_to countries_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/states_controller.rb
class StatesController < ApplicationController

	# Display a list of States
	# GET /states
	# GET /states.json
	def index
		@states = State.all

		respond_to do |format|
			format.html #index.html.erb
			format.json { render json: @states }
		end
	end

	# Display details of a single State
	# GET /states/1
	# GET /states/1.json
	def show
		@state = State.find(params[:id])

		respond_to do |format|
			format.html #show.html.erb
			format.json { render json: @state }
		end
	end

	# Display form to gather data for a new State
	# GET /states/new
	# GET /states/new.json
	def new
		@state = State.new

		respond_to do |format|
			format.html #new.html.erb
			format.json { render json: @state }
		end
	end
	
	# Create a new State
	# POST /countries
	# POST /countries.json
	def create
		@state = State.new(params[:state])
		@country = Country.find_by_iso_code(@state.country_iso_code)
		if (@country.nil?)
			format.html { render action: "new" }
			format.json { render json: @state.errors, status: :unprocessable_entity }
		else
			@state.country = @country
			@country.states.append @state
		end

		respond_to do |format|
			if @state.save && @country.save
				format.html { redirect_to @state, notice: "State was successfully created" }
				format.json { render json: @state, status: :created, location: @state }
			else
				format.html { render action: "new"}
				format.json { render json: @state.errors, status: :unprocessable_entity }
			end
		end
	end

	# Display form to gather data to edit an existing State
	# GET /states/1/edit
	# GET /states/1/edit.json
	def edit
		@state = State.find(params[:id])
	end

	# Update an existing State
	def update
		@state = State.find(params[:id])

		if @state.country_iso_code != params[:state][:country_iso_code]
			@old_country = @state.country
			@new_country = Country.find_by_iso_code(params[:state][:country_iso_code])
			if ! @new_country.nil?
				@old_country.states.delete @state
				@old_country.save

				@new_country.states.append @state
				@new_country.save

				@state.country = @new_country
				@state.save
			end
		end

		respond_to do |format|
			if @state.update_attributes(params[:state])
				format.html { redirect_to @state, notice: "State was successfully updated" }
				format.json { head :no_content }
			else
				format.html { render action: "edit" }
				format.json { render json: @state.errors, status: :unprocessable_entity }
			end
		end
	end

	# Destroy an existing State
	# DELETE /states/1
	# DELTE /states/1.json
	def destroy
		@state = State.find(params[:id])

		@country = @state.country
		@country.states.delete @state

		@country.save
		@state.destroy

		respond_to do |format|
			format.html { redirect_to states_url }
			format.json { head :no_content }
		end
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/countries_helper.rb
module CountriesHelper
end

app/helpers/states_helper.rb
module StatesHelper
end

app/views/countries/_form.html.erb
<%= form_for(@country, html: { class: "form-horizontal"} ) do |f| %>
<fieldset>
  <legend>Country</legend>
  <% if @country.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@country.errors.count, "error") %> prohibited this country from being saved:</h2>

    <ul>
      <% @country.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
  <% end %>

  <div class="control-group>">
    <%= f.label :iso_code, class: "control-label" %><br />
    <div class="controls">
      <%= f.text_field :iso_code %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :name, class: "control-label" %><br />
    <div class="controls">
      <%= f.text_field :name %>
    </div>
  </div>
  
  <div class="control-group">
    <div class="controls">
      <%= f.submit class: "btn btn-primary" %>
    </div>
  </div>
  
</fieldset>
<% end %>

app/views/countries/edit.html.erb
<h1>Editing country</h1>
<div class="row-fluid">
	<div class="span4 offset4">
		<%= render 'form' %>

		<i class="icon-list"></i>
		<%= link_to 'Show', @country %> |
		<i class="icon-circle-arrow-left"></i>
		<%= link_to 'Back', countries_path %>
	</div>
</div>

app/views/countries/index.html.erb
<h1>Countries</h1>

<div class="row-fluid">
  <div class="span4 offset4">
    <table class="table table-stripped table-bordered table-condensed">
      <tr>
        <th>ISO</th>
        <th>Name</th>
        <th></th>
        <th></th>
        <th></th>
      </tr>

      <% @countries.each do |country| %>
      <tr>
        <td><%= country.iso_code %></td>
        <td><%= country.name %></td>
        <td>
          <%= link_to country do %>
          <i class="icon-list"></i>
          <% end %>
        </td>
        <td>
          <%= link_to edit_country_path(country) do %>
          <i class="icon-edit"></i>
          <% end %>
        </td>
        <td>
          <%= link_to country, method: :delete, data: { confirm: 'Are you sure?' } do %>
          <i class="icon-remove"></i>
          <% end %>
        </td>
      </tr>
      <% end %>
    </table>

    <br />
    <i class="icon-plus"></i>
    <%= link_to 'New Country', new_country_path %>
  </div><!--span4-->
</div><!--row-fluid-->

app/views/countries/new.html.erb
<h1>New country</h1>

<div class="row-fluid">
	<div class="span4 offset4">
		<%= render 'form' %>
		<i class="icon-circle-arrow-left"></i>
		<%= link_to 'Back', countries_path %>
	</div>
</div>

app/views/countries/show.html.erb
<p id="notice"><%= notice %></p>

<div class="row-fluid">
	<div class="span4 offset4">
		<p>
  			<b>ISO Code:</b>
  			<%= @country.iso_code %>
		</p>

		<p>
  			<b>Name:</b>
  			<%= @country.name %>
		</p>

		<i class="icon-edit"></i>
		<%= link_to 'Edit', edit_country_path(@country) %> |
		<i class="icon-circle-arrow-left"></i>
		<%= link_to 'Back', countries_path %>
	</div>
</div>

app/views/layouts/_shim.html.erb
  <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
  <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CRUD Test</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>

  <%= render 'layouts/shim' %>
</head>
<body>
  <div class="container-fluid">
<%= yield %>
  </div><!-- container -->
</body>
</html>

app/views/states/_form.html.erb
<%= form_for(@state, html: { class: "form-horizontal" } ) do |f| %>
<fieldset>
  <legend>State</legend>
  <% if @state.errors.any? %>
  <div id="error-explanation">
    <h2><%= pluralize(@state.errors.count, "error") %> prohibited this state from being saved:</h2>

    <ul>
      <% @state.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
  <% end %>

  <div class="countrol-group">
  	<%= f.label :country_iso_code, class: "control-label" %><br />
  	<div class="controls">
  	  <%= f.text_field :country_iso_code %>
  	</div>
  </div>

  <div class="countrol-group">
  	<%= f.label :state_code, class: "control-label" %><br />
  	<div class="controls">
      <%= f.text_field :state_code %>
  	</div>
  </div>

  <div class="countrol-group">
  	<%= f.label :name, class: "control-label" %><br />
  	<div class="controls">
  	  <%= f.text_field :name %>
  	</div>
  </div>

  <div class="countrol-group">
  	<%= f.submit class: "btn btn-primary" %>
  </div>

</fieldset>
<!--form-->
<% end %>

app/views/states/edit.html.erb
<h1>Edit State</h1>

<div class="row-fluid">
	<div class="span4 offset4">
		<%= render 'form' %>

		<i class="icon-list"></i>
		<%= link_to 'Show', @state %>
		<i class="icon-circle-left-arrow"></i>
		<%= link_to 'Back', states_path %>
	</div>
</div>

app/views/states/index.html.erb
<h1>States</h1>

<div class="row-fluid">
  <div class="span4 offset4">
    <table class="table table-stripped table-bordered table-condensed">
  	  <tr>
  	    <th>Country</th>
  	   	<th>Code</th>
  	   	<th>Name</th>
  	   	<th></th>
  	   	<th></th>
  	   	<th></th>
  	  </tr>
  	  <% @states.each do |state| %>
  	  <tr>
  	    <td><%= state.country_iso_code %></td>
  	    <td><%= state.state_code %></td>
  	    <td><%= state.name %></td>
  	    <td>
  	      <%= link_to state do %>
  	      <i class="icon-list"></i>
  	      <% end %>
  	    </td>
  	    <td>
  	      <%= link_to edit_state_path(state) do %>
  	      <i class="icon-edit"></i>
  	      <% end %>
  	    </td>
  	    <td>
  	      <%= link_to state, method: :delete, data: { confirm: 'Are you sure?' } do %>
  	      <i class="icon-remove"></i>
  	      <% end %> 
  	    </td>
  	  </tr>
      <% end %>
    </table>
 
    <br />
    <i class="icon-plus"></i>
    <%= link_to 'New State', new_state_path %>

  </div><!-- span4 -->
</div><!-- row-fluid -->

app/views/states/new.html.erb
<h1>New State</h1>

<div class="row-fluid">
	<div class="span4 offset4">
		<%= render 'form' %>
		<i class="icon-circle-arrow-left"></i>
		<%= link_to 'Back', states_path %>
	</div>
</div>

app/views/states/show.html.erb
<p id="notice"><%= notice %>
<div class="row-fluid">
	<div class="span4 offset4">
		<p>
			<b>Country:</b>
			<%= @state.country.name %>
		</p>

		<p>
			<b>Code:</b>
			<%= @state.state_code %>
		</p>

		<p>
			<b>Name:</b>
			<%= @state.name %>
		</p>

		<i class="icon-edit"></i>
		<%= link_to 'Edit', edit_state_path(@state) %>
		<i class="icon-circle-arrow-left"></i>
		<%= link_to 'Back', states_path %>
	</div>
</div>